development:
  adapter: postgresql
  encoding: unicode
  database: api_development
  pool: 5
  username: yechielk
  password: Yk987789

test:
  adapter: postgresql
  encoding: unicode
  database: api_test
  pool: 5
  username: yechielk
  password: Yk987789